exercism/zig

.github/dependabot.yml, .github/workflows/configlet.yml, bin/fetch-configlet, bin/fetch-configlet.ps1, config.json
_This PR is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._
This PR prepares the track for Exercism v3, which will be different in a number of ways from Exercism v2.
As having this PR merged is essential to prepare this track for Exercism v3, we'll automatically merge this PR one week after it was opened (if it hasn't been merged already).
In this PR, the following changes are made:
1. Move the existing exercises in the `exercises` directory to the `exercises/practice` directory
The `config.json` file is updated to conform to the [v3 spec](https://github.com/exercism/v3-docs/blob/main/anatomy/tracks/config-json.md).
1. Add a version property:
```json
"version": 3
```
2. Add online editor settings:
```json …
```
=> [v3] Prepare for v3

config/exercise-readme-insert.md, docs/ABOUT.md, docs/INSTALLATION.md, docs/LEARNING.md, docs/RESOURCES.md, docs/TESTS.md
We've defined a [specification for Markdown files](https://github.com/exercism/docs/blob/main/contributing/standards/markdown.md) to be applied Exercism-wide. This standard includes, amongst others, the following two rules:
- All files must start start with a level-1 heading (`# Some heading text`)
- No heading may decend a level greater than one below the previous (e.g. `## may only be followed by ###, not ####`)
This PR applies the above two rules to the Markdown documents in this repo. 
https://github.com/exercism/v3-launch/issues/17
=> [v3] Update Markdown files to latest spec

.gitignore, .travis.yml, config.json
- zig-cache directories are ignored, so files involving compilation output are never accidentally pushed onto the repo. 
- The repo's config.js file now contains some Zig related information, including tags. Thus, this pull request should resolve issue #14 entirely.
- Finally, the .travis.yml file has been removed. This is the first step towards resolving issue #2.
=> Add Zig related miscellaneous information

_test/run-tests.sh, config.json, exercises/practice/hello-world/.docs/instructions.md, exercises/practice/hello-world/.meta/config.json, exercises/practice/hello-world/.meta/example.zig, exercises/practice/hello-world/.meta/tests.toml, exercises/practice/hello-world/hello_world.zig, exercises/practice/hello-world/test_hello_world.zig
- A Zig implementation of the Exercism standard hello-world practice exercise.
**Note**: This practice exercise's "practices" and "prerequisites" keys within the track's config.json file will have to change at a later date. The placeholder values are accurate to what has to be understood before grasping this practice exercise. It's just that those key's values are speculative as to what concepts will exist and how they will flow when later designed and implemented.
=> Add hello-world practice exercise

config.json, exercises/practice/two-fer/.docs/instructions.md, exercises/practice/two-fer/.meta/config.json, exercises/practice/two-fer/.meta/example.zig, exercises/practice/two-fer/.meta/tests.toml, exercises/practice/two-fer/test_two_fer.zig, exercises/practice/two-fer/two_fer.zig
- A Zig implementation of the Exercism standard two-fer practice exercise.
=> Add two-fer practice exercise

config.json, exercises/practice/difference-of-squares/.docs/instructions.md, exercises/practice/difference-of-squares/.meta/config.json, exercises/practice/difference-of-squares/.meta/example.zig, exercises/practice/difference-of-squares/.meta/tests.toml, exercises/practice/difference-of-squares/difference_of_squares.zig, exercises/practice/difference-of-squares/test_difference_of_squares.zig
- A Zig implementation of the Exercism standard difference-of-squares practice exercise.
=> Add difference-of-squares practice exercise

config.json, exercises/practice/resistor-color/.docs/instructions.md, exercises/practice/resistor-color/.meta/config.json, exercises/practice/resistor-color/.meta/example.zig, exercises/practice/resistor-color/.meta/tests.toml, exercises/practice/resistor-color/resistor_color.zig, exercises/practice/resistor-color/test_resistor_color.zig
- A Zig implementation of the Exercism standard resistor-color practice exercise.
=> Add resistor-color practice exercise

config.json, exercises/practice/grains/.docs/instructions.md, exercises/practice/grains/.meta/config.json, exercises/practice/grains/.meta/example.zig, exercises/practice/grains/.meta/tests.toml, exercises/practice/grains/grains.zig, exercises/practice/grains/test_grains.zig
- A Zig implementation of the Exercism standard grains practice exercise.
=> Add grains practice exercise

config.json, exercises/practice/resistor-color-duo/.docs/instructions.md, exercises/practice/resistor-color-duo/.meta/config.json, exercises/practice/resistor-color-duo/.meta/example.zig, exercises/practice/resistor-color-duo/.meta/tests.toml, exercises/practice/resistor-color-duo/resistor_color_duo.zig, exercises/practice/resistor-color-duo/test_resistor_color_duo.zig
- A Zig implementation of the Exercism standard resistor-color-duo practice exercise.
- Also fixes a problem between the resistor-color and resistor-color-duo entries in the track's config.json file. They were added incorrectly in different pull requests. This pull request will add resistor-color into the track's config.json file and alter the existing resistor-color-duo to actually match the specifications of the implemented exercise.
Note: This practice exercise's "practices" and "prerequisites" keys within the track's config.json file will have to change at a later date. The placeholder values are accurate to what has to be understood before grasping this practice exercise. It's just that those key's values are speculative as to what concepts will …
=> Add resistor-color-duo practice exercise

config.json, exercises/practice/darts/.docs/instructions.md, exercises/practice/darts/.meta/config.json, exercises/practice/darts/.meta/example.zig, exercises/practice/darts/.meta/tests.toml, exercises/practice/darts/darts.zig, exercises/practice/darts/test_darts.zig
- A Zig implementation of the Exercism standard darts practice exercise.
=> Add darts practice exercise

config.json, exercises/practice/hamming/.docs/instructions.md, exercises/practice/hamming/.meta/config.json, exercises/practice/hamming/.meta/example.zig, exercises/practice/hamming/.meta/tests.toml, exercises/practice/hamming/hamming.zig, exercises/practice/hamming/test_hamming.zig
- A Zig implementation of the Exercism standard hamming practice exercise.
=> Add hamming practice exercise

config.json, exercises/practice/leap/.docs/instructions.md, exercises/practice/leap/.meta/config.json, exercises/practice/leap/.meta/example.zig, exercises/practice/leap/.meta/tests.toml, exercises/practice/leap/leap.zig, exercises/practice/leap/test_leap.zig
- A Zig implementation of the Exercism standard leap practice exercise.
=> Add leap practice exercise

config.json, exercises/practice/triangle/.docs/instructions.md, exercises/practice/triangle/.meta/config.json, exercises/practice/triangle/.meta/example.zig, exercises/practice/triangle/.meta/tests.toml, exercises/practice/triangle/test_triangle.zig, exercises/practice/triangle/triangle.zig
- A Zig implementation of the Exercism standard triangle practice exercise.
=> Add triangle practice exercise

config.json, exercises/practice/pangram/.docs/instructions.md, exercises/practice/pangram/.meta/config.json, exercises/practice/pangram/.meta/example.zig, exercises/practice/pangram/.meta/tests.toml, exercises/practice/pangram/pangram.zig, exercises/practice/pangram/test_pangram.zig
- A Zig implementation of the Exercism standard pangram practice exercise.
=> Add pangram practice exercise

config.json, exercises/practice/rna-transcription/.docs/instructions.md, exercises/practice/rna-transcription/.meta/config.json, exercises/practice/rna-transcription/.meta/example.zig, exercises/practice/rna-transcription/.meta/tests.toml, exercises/practice/rna-transcription/rna_transcription.zig, exercises/practice/rna-transcription/test_rna_transcription.zig
- A Zig implementation of the Exercism standard rna-transcription practice exercise.
=> Add rna-transcription practice exercise

config.json, exercises/practice/space-age/.docs/instructions.md, exercises/practice/space-age/.meta/config.json, exercises/practice/space-age/.meta/example.zig, exercises/practice/space-age/.meta/tests.toml, exercises/practice/space-age/space_age.zig, exercises/practice/space-age/test_space_age.zig
- A Zig implementation of the Exercism standard space-age practice exercise.
=> Add space-age practice exercise

exercises/practice/collatz-conjecture/.meta/config.json, exercises/practice/darts/.meta/config.json, exercises/practice/difference-of-squares/.meta/config.json, exercises/practice/grains/.meta/config.json, exercises/practice/hamming/.meta/config.json, exercises/practice/hello-world/.meta/config.json, exercises/practice/leap/.meta/config.json, exercises/practice/pangram/.meta/config.json, exercises/practice/resistor-color-duo/.meta/config.json, exercises/practice/resistor-color/.meta/config.json, exercises/practice/rna-transcription/.meta/config.json, exercises/practice/space-age/.meta/config.json, exercises/practice/triangle/.meta/config.json, exercises/practice/two-fer/.meta/config.json
The authors and contributors of exercises are stored in an array of objects in the exercises' `.meta/config.json` files.
Each author/contributor used to have two properties: their GitHub username _and_ their Exercism username.
As we're only using the GitHub username, we're flattening the `authors` and `contributors` array to an array of strings representing the GitHub usernames.
We will update `configlet` to validate the new structure, so you might be seeing build failures once we've implemented this change. 
See https://github.com/exercism/docs/pull/90/files
We will automatically merge this PR immediately to be able to submit a different PR in which we'll add the authors/contributors for practice exercises.
https://github.com/exercism/v3-launch/issues/26
=> 🤖 Flatten authors and contributors in .meta/config.json files

config.json, exercises/practice/queen-attack/.docs/instructions.md, exercises/practice/queen-attack/.meta/config.json, exercises/practice/queen-attack/.meta/example.zig, exercises/practice/queen-attack/.meta/tests.toml, exercises/practice/queen-attack/test_queen_attack.zig
- A Zig implementation of the Exercism standard queen-attack practice exercise.
=> Add queen-attack practice exercise

exercises/practice/queen-attack/.meta/config.json
- A correction to the queen-attack exercise config.json file. This will flatten the authors and contributors of the exercises into one name.
=> Flatten queen-attack authors

config.json, exercises/practice/binary-search/.docs/instructions.md, exercises/practice/binary-search/.meta/config.json, exercises/practice/binary-search/.meta/example.zig, exercises/practice/binary-search/.meta/tests.toml, exercises/practice/binary-search/binary_search.zig, exercises/practice/binary-search/test_binary_search.zig
- A Zig implementation of the Exercism standard binary-search practice exercise.
=> Add binary-search practice exercise

config.json, exercises/practice/secret-handshake/.docs/instructions.md, exercises/practice/secret-handshake/.meta/config.json, exercises/practice/secret-handshake/.meta/example.zig, exercises/practice/secret-handshake/.meta/tests.toml, exercises/practice/secret-handshake/secret_handshake.zig, exercises/practice/secret-handshake/test_secret_handshake.zig
- A Zig implementation of the Exercism standard secret-handshake practice exercise.
=> Add secret-handshake practice exercise

config.json, exercises/practice/isogram/.docs/instructions.md, exercises/practice/isogram/.meta/config.json, exercises/practice/isogram/.meta/example.zig, exercises/practice/isogram/.meta/tests.toml, exercises/practice/isogram/isogram.zig, exercises/practice/isogram/test_isogram.zig
- A Zig implementation of the Exercism standard isogram practice exercise.
=> Add isogram practice exercise

config.json, exercises/practice/proverb/.docs/instructions.md, exercises/practice/proverb/.meta/config.json, exercises/practice/proverb/.meta/example.zig, exercises/practice/proverb/.meta/tests.toml, exercises/practice/proverb/proverb.zig, exercises/practice/proverb/test_proverb.zig
- A Zig implementation of the Exercism standard proverb practice exercise.
=> Add proverb practice exercise

exercises/practice/binary-search/.meta/tests.toml, exercises/practice/collatz-conjecture/.meta/tests.toml, exercises/practice/darts/.meta/tests.toml, exercises/practice/difference-of-squares/.meta/tests.toml, exercises/practice/grains/.meta/tests.toml, exercises/practice/hamming/.meta/tests.toml, exercises/practice/hello-world/.meta/tests.toml, exercises/practice/isogram/.meta/tests.toml, exercises/practice/leap/.meta/tests.toml, exercises/practice/pangram/.meta/tests.toml, exercises/practice/proverb/.meta/tests.toml, exercises/practice/queen-attack/.meta/tests.toml, exercises/practice/resistor-color-duo/.meta/tests.toml, exercises/practice/resistor-color/.meta/tests.toml, exercises/practice/rna-transcription/.meta/tests.toml, exercises/practice/secret-handshake/.meta/tests.toml, exercises/practice/space-age/.meta/tests.toml, exercises/practice/triangle/.meta/tests.toml, exercises/practice/two-fer/.meta/tests.toml
This PR simplifies the `tests.toml` files by removing any `include = true` properties, which are redundant as the default value of this field is `true`.
As the vast majority of the test cases use `include = true`, omitting it makes the `tests.toml` files more readable and make the exceptional cases (`include = false`) easier to identify.
We've updated `configlet` to use this new behavior. See https://github.com/exercism/configlet/issues/186 and https://github.com/exercism/configlet/issues/207 for the corresponding discussion.
https://github.com/exercism/v3-launch/issues/31
=> 🤖 Simplify tests.toml files

exercises/practice/collatz-conjecture/.meta/config.json, exercises/practice/darts/.meta/config.json, exercises/practice/difference-of-squares/.meta/config.json, exercises/practice/grains/.meta/config.json, exercises/practice/hamming/.meta/config.json, exercises/practice/hello-world/.meta/config.json, exercises/practice/leap/.meta/config.json, exercises/practice/pangram/.meta/config.json, exercises/practice/resistor-color-duo/.meta/config.json, exercises/practice/resistor-color/.meta/config.json, exercises/practice/rna-transcription/.meta/config.json, exercises/practice/space-age/.meta/config.json, exercises/practice/triangle/.meta/config.json, exercises/practice/two-fer/.meta/config.json
_If you got tagged in this PR, it is because you are being credited for work you've done in the past on Exercism here, and we want to ensure you don't miss out on the recognition you deserve 🙂_
---
With v3, we've introduced the idea of exercise authors and contributors. This information is stored in the exercises' `.meta/config.json` files (see [the docs](https://github.com/exercism/docs/blob/main/building/tracks/practice-exercises.md#file-metaconfigjson)).
Concept Exercises, which are all new, already contain authors and contributors. Practice Exercises though are missing this information. In this PR, we attempt to populate the authors and contributors of Practice Exercises based on their commit history.
These are the things you, the maintainers, should do:
**For clarity, authors should …
=> 🤖 Add authors and contributors to Practice Exercises

exercises/practice/hello-world/hello_world.zig
Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46
=> 🤖 Simplify `hello-world` stub

config.json
From [the spec](https://github.com/exercism/docs/blob/14de83e5305b/building/configlet/lint.md#rule-configjson-file-is-valid):
> - The `"exercises.practice[].prerequisites"` value must be an empty
array if `"exercises.practice[].slug"` is equal to `hello-world`
This would otherwise cause `configlet lint` to produce an error in the future (and might stop `hello-world` from being unlocked!).
=> Remove prerequisites from `hello-world`

exercises/practice/binary-search/test_binary_search.zig, exercises/practice/collatz-conjecture/test_collatz_conjecture.zig, exercises/practice/darts/test_darts.zig, exercises/practice/difference-of-squares/test_difference_of_squares.zig, exercises/practice/grains/test_grains.zig, exercises/practice/hamming/test_hamming.zig, exercises/practice/hello-world/test_hello_world.zig, exercises/practice/isogram/test_isogram.zig, exercises/practice/leap/test_leap.zig, exercises/practice/pangram/test_pangram.zig, exercises/practice/proverb/test_proverb.zig, exercises/practice/queen-attack/test_queen_attack.zig, exercises/practice/resistor-color-duo/test_resistor_color_duo.zig, exercises/practice/resistor-color/test_resistor_color.zig, exercises/practice/rna-transcription/.meta/example.zig, exercises/practice/rna-transcription/test_rna_transcription.zig, exercises/practice/secret-handshake/test_secret_handshake.zig, exercises/practice/space-age/test_space_age.zig, exercises/practice/triangle/test_triangle.zig, exercises/practice/two-fer/.meta/example.zig, exercises/practice/two-fer/test_two_fer.zig
- try seems required before testing operations now
- use newer API expectApproxEqRel
All tests run now on 0.8.1 other than `space-age`.  Could use help there.
---
This fixes all tests (on 0.8.1) other than `space-age`.
```
/usr/local/Cellar/zig/0.8.1/lib/zig/std/testing.zig:264:27: error: Cannot approximately compare two comptime_float values
.ComptimeFloat => @compileError("Cannot approximately compare two comptime_float values"),
```
I did correct to the new API, but there still seems to be another issue.
=> fixup: get tests working again

exercises/shared/.docs/help.md, exercises/shared/.docs/tests.md
This commit resolves an error from `configlet lint`.
From the Exercism [docs](https://exercism.org/docs/building/tracks/shared-files) on these so-called "shared files":
> - help.md: contains track-specific instructions on how to get help (required)
> - tests.md: contains track-specific instructions on how to run the tests (required)
=> docs: add shared docs

.github/workflows/tests.yml
Looks like it's best to do this before bumping to 0.9.1.
Related: #104
Related: #99
This makes a bunch of exercise tests pass, but not those for `space-age`.
=> ci: bump Zig from 0.7.0 to 0.8.1

.github/bin/install-zig.sh, exercises/practice/proverb/.meta/example.zig, exercises/practice/proverb/proverb.zig, exercises/practice/rna-transcription/.meta/example.zig, exercises/practice/rna-transcription/rna_transcription.zig, exercises/practice/secret-handshake/.meta/example.zig, exercises/practice/secret-handshake/secret_handshake.zig
See the release notes for Zig [0.9.0][1] and [0.9.1][2].
Upgrading Zig produced errors like:
```text
./test_proverb.zig:12:46: error: expected type '*std.mem.Allocator', found 'std.mem.Allocator'
const actual = try proverb.recite(testing.allocator, input_slice);
^
/foo/zig-linux-x86_64-0.9.1/lib/std/mem/Allocator.zig:1:1: note: std.mem.Allocator declared here
//! The standard memory allocation interface.
^
```
So this PR must also fix the errors by following the advice from the [Zig 0.9.0 release notes][3]:
>The `mem.Allocator` interface has changed in a breaking way.
>
>In short summary, here is how to change your code:
>
>- Change `*Allocator` to `Allocator` in function parameter types and struct field types.
>
>- Instead of taking the pointer to an allocator field, such as …
=> install-zig, exercises: bump Zig from 0.8.1 to 0.9.1

.github/bin/install-zig.sh, exercises/practice/leap/.meta/example.zig, exercises/practice/two-fer/.meta/example.zig
See the release notes for Zig [0.10.0][1] and [0.10.1][2].
Zig 0.10.1 produced these errors for the previous example solutions for `leap` and `two-fer`:
```console
$ zig test test_leap.zig
leap.zig:8:21: error: no field named 'has_factor' in struct 'leap.leap__struct_1016'
}{ .y = year }).has_factor;
^~~~~~~~~~
leap.zig:2:25: note: struct declared here
const has_factor = (struct {
^~~~~~
test_leap.zig:7:43: note: called from here
comptime try testing.expect(!leap.leap(2015));
~~~~~~~~~^~~~~~
```
```console
$ zig test -freference-trace test_two_fer.zig
/foo/zig-linux-x86_64-0.10.1/lib/std/fmt.zig:498:17: error: cannot format optional without a specifier (i.e. {?} or {any})
@compileError("cannot format optional without a specifier (i.e. {?} or {any})"); …
```
=> install-zig, exercises: bump Zig from 0.9.1 to 0.10.1

exercises/practice/hello-world/test_hello_world.zig
I think the simplest thing for now is to just remove the `comptime`. There is no other `comptime` use of `expectEqualStrings` in this repo.
We could instead use `mem.eql` like this:
```diff
const std = @import("std");
+const mem = std.mem;
const testing = std.testing;
const hello_world = @import("hello_world.zig");
test "say hi" {
const expected = "Hello, world!";
const actual = comptime hello_world.hello();
-    comptime try testing.expectEqualStrings(expected, actual);
+    comptime try testing.expect(mem.eql(u8, expected, actual));
```
but then the test failure message is less useful:
```console
$ zig test test_hello_world.zig
Test [1/1] test.say hi... FAIL (TestUnexpectedResult)
/foo/exercism-tracks/zig/exercises/practice/hello-world/test_hello_world.zig:10:40: 0x20eee7 in test.say hi …
```
=> exercises(hello-world): test: handle incorrect solution better

.github/workflows/configlet.yml
From the [configlet workflow log for this PR](https://github.com/exercism/zig/actions/runs/4092066220/jobs/7056546121#step:5:5):
```text
Found 0 Concept Exercises and 19 Practice Exercises in /home/runner/work/zig/zig/config.json
Looking for exercises that lack a formatted '.meta/config.json' file...
Every exercise config is already formatted!
```
=> .github: enable `configlet fmt` in CI

config.json
This seems to better reflect the actual average run time.
=> Update average test runner time

exercises/practice/difference-of-squares/.meta/example.zig, exercises/practice/difference-of-squares/difference_of_squares.zig, exercises/practice/difference-of-squares/test_difference_of_squares.zig, exercises/practice/resistor-color-duo/.meta/example.zig, exercises/practice/resistor-color-duo/resistor_color_duo.zig, exercises/practice/resistor-color-duo/test_resistor_color_duo.zig, exercises/practice/resistor-color/.meta/example.zig, exercises/practice/resistor-color/resistor_color.zig, exercises/practice/resistor-color/test_resistor_color.zig, exercises/practice/rna-transcription/test_rna_transcription.zig, exercises/practice/two-fer/.meta/example.zig, exercises/practice/two-fer/test_two_fer.zig, exercises/practice/two-fer/two_fer.zig
From the [Zig Style Guide][1]:
> Roughly speaking: `camelCaseFunctionName`, `TitleCaseTypeName`, `snake_case_variable_name`. More precisely:
> 
> - If `x` is a `type` then `x` should be `TitleCase`, unless it is a `struct` with 0 fields and is never meant to be instantiated, in which case it is considered to be a "namespace" and uses `snake_case`.
> 
> - If `x` is callable, and `x`'s return type is `type`, then `x` should be `TitleCase`.
> 
> - If `x` is otherwise callable, then `x` should be `camelCase`.
> 
> - Otherwise, `x` should be `snake_case`.
[1]: https://ziglang.org/documentation/0.10.1/#Style-Guide
=> exercises: use camelCase for function names

exercises/practice/grains/.meta/example.zig, exercises/practice/space-age/.meta/example.zig, exercises/practice/two-fer/test_two_fer.zig
From the [Zig Style Guide][1]:
> Roughly speaking: `camelCaseFunctionName`, `TitleCaseTypeName`, `snake_case_variable_name`. More precisely:
> 
> - If `x` is a `type` then `x` should be `TitleCase`, unless it is a `struct` with 0 fields and is never meant to be instantiated, in which case it is considered to be a "namespace" and uses `snake_case`.
> 
> - If `x` is callable, and `x`'s return type is `type`, then `x` should be `TitleCase`.
> 
> - If `x` is otherwise callable, then `x` should be `camelCase`.
> 
> - Otherwise, `x` should be `snake_case`.
[1]: https://ziglang.org/documentation/0.10.1/#Style-Guide
=> exercises: use snake_case for variable names

exercises/practice/hamming/.meta/example.zig, exercises/practice/hamming/hamming.zig, exercises/practice/hamming/test_hamming.zig, exercises/practice/rna-transcription/.meta/example.zig, exercises/practice/rna-transcription/rna_transcription.zig, exercises/practice/rna-transcription/test_rna_transcription.zig
From the [Zig Style Guide][1]:
> Roughly speaking: `camelCaseFunctionName`, `TitleCaseTypeName`, `snake_case_variable_name`. More precisely:
> 
> - If `x` is a `type` then `x` should be `TitleCase`, unless it is a `struct` with 0 fields and is never meant to be instantiated, in which case it is considered to be a "namespace" and uses `snake_case`.
> 
> - If `x` is callable, and `x`'s return type is `type`, then `x` should be `TitleCase`.
> 
> - If `x` is otherwise callable, then `x` should be `camelCase`.
> 
> - Otherwise, `x` should be `snake_case`.
>
> Acronyms, initialisms, proper nouns, or any other word that has capitalization rules in written English are subject to naming conventions just like any other word. Even acronyms that are only 2 letters long are subject to these …
=> exercises: use camelCase for acronyms

README.md
This repo no longer uses Travis CI. Commit 1af7db247621 removed the `.travis.yml` file.
=> README: remove Travis CI badge

exercises/practice/collatz-conjecture/.meta/config.json, exercises/practice/darts/.meta/config.json, exercises/practice/difference-of-squares/.meta/config.json, exercises/practice/grains/.meta/config.json, exercises/practice/hamming/.meta/config.json, exercises/practice/hello-world/.meta/config.json, exercises/practice/leap/.meta/config.json, exercises/practice/pangram/.meta/config.json, exercises/practice/resistor-color-duo/.meta/config.json, exercises/practice/resistor-color/.meta/config.json, exercises/practice/rna-transcription/.meta/config.json, exercises/practice/space-age/.meta/config.json, exercises/practice/triangle/.meta/config.json, exercises/practice/two-fer/.meta/config.json
These were present due to Exercism-wide PRs, which aren't supposed to count towards `contributors` (see commit message for 973e7548eb11, and [docs](https://github.com/exercism/docs/blob/6a0731ff768f/building/tracks/practice-exercises.md#file-metaconfigjson)).
---
GitHub links:
- https://github.com/exercism/zig/commits?author=ErikSchierboom
- https://github.com/exercism/zig/commits?author=ihid
@ErikSchierboom please let me know if https://github.com/exercism/zig/commit/00505196ce96a1963b83b67f732b6c12bf7d70f4 should count.
=> exercises: remove ErikSchierboom and iHiD from contributors

exercises/practice/triangle/test_triangle.zig
The test immediately above is identical.
I've checked that we should remove the test in this PR, rather than changing the values - the number of implemented tests now matches the number of tests in `.meta/tests.toml`:
https://github.com/exercism/zig/blob/a0b53c56d0b5ac35988eb7b91495bcdbd50dbdfd/exercises/practice/triangle/.meta/tests.toml#L57-L67
I'll add the new upstream tests in a follow-up PR.
=> exercises(triangle): remove duplicate test

exercises/practice/space-age/space_age.zig
Before this commit, when testing the stub solution:
```console
$ zig test test_space_age.zig
space_age.zig:12:16: error: expected expression, found 'invalid bytes'
@panic("please implement the
^~~~~~~~~~~~~~~~~~~~~
space_age.zig:12:37: note: invalid byte: '\n'
@panic("please implement the
```
With this commit:
```console
$ zig test test_space_age.zig
space_age.zig:7:17: error: unused function parameter
pub fn init(seconds: isize) SpaceAge {
^~~~~~~
space_age.zig:11:58: error: use of undeclared identifier 'Planet'
fn getOrbitalPeriodInSecondsFromEarthYearsOf(planet: Planet) f64 {
^~~~~~
space_age.zig:15:47: error: use of undeclared identifier 'Planet'
fn getOrbitalPeriodInEarthYearsOf(planet: Planet) f64 {
^~~~~~
space_age.zig:19:22: error: unused function parameter
pub fn onMercury(self: …
```
=> exercises(space-age): stub: fix error

exercises/practice/two-fer/.meta/example.zig, exercises/practice/two-fer/test_two_fer.zig
The implementation of this exercise didn't match the [instructions](https://github.com/exercism/zig/blob/07e3c82c9accc31a6d18bf807a2b3c06b78b0ab6/exercises/practice/two-fer/.docs/instructions.md), which specify:
> Given a name, return a string with the message:
> 
> ```text
> One for name, one for me.
> ```
> 
> Where "name" is the given name.
> 
> However, if the name is missing, return the string:
> 
> ```text
> One for you, one for me.
> ```
---
The mismatch was present in the commit that added the exercise: https://github.com/exercism/zig/commit/639ecd6ef9f5ae950aa1d87aae9cc8792d83805e
=> exercises(two-fer): fix twoFer returned values

docs/ABOUT.md, docs/INSTALLATION.md, docs/LEARNING.md, docs/RESOURCES.md, docs/TESTS.md, exercises/shared/.docs/help.md
Comply with the [Exercism Markdown Specification][1]:
>Paragraphs should be laid at using one sentence per line.
>The [Ascii Doctor docs][2] explain the logic of this clearly.
>
>For example, a single paragraph should be laid out as follows:
>
>```
>Exercism has been designed, engineered and built by thousands of very talented individuals.
>Nearly everything with Exercism has been debated, discussed and rewritten many times.
>Exercism is a very intentional product - things are there because they've been designed to be there, and things are often left out because they've been designed to be left out.
>```
[1]: https://github.com/exercism/docs/blob/6a0731ff768f/building/markdown/markdown.md#one-sentence-per-line
[2]: https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-p …
=> docs: use one sentence per line

docs/LEARNING.md
The previously linked repo was last updated on 2020-11-14. There are at least two awesome-zig repos (by C-BJ and catdevnull) that we could link to instead. For now let's use catdevnull's, which is the one [currently mentioned in the Zig Wiki][1] and in [the most starred "awesome list" on GitHub][2].
[1]: https://github.com/ziglang/zig/wiki/Community-Projects
[2]: https://github.com/sindresorhus/awesome/tree/c9da614a2b71#programming-languages
---
Alternative to https://github.com/exercism/zig/pull/158.
=> docs(LEARNING): update awesome-zig link

exercises/practice/grains/test_grains.zig
Zig does not have exceptions.
Closes: #144
---
With this PR, we have no more user-facing mentions of "exception":
```console
$ git rev-parse --short HEAD
337cd46
$ git grep --break --heading 'exception'
exercises/practice/grains/.meta/tests.toml
34:description = "returns the number of grains on the square -> square 0 raises an exception"
37:description = "returns the number of grains on the square -> negative square raises an exception"
40:description = "returns the number of grains on the square -> square greater than 64 raises an exception"
```
=> exercises(grains): talk about errors, not exceptions

.github/workflows/zig-fmt.yml
Closes: #194
---
```console
$ zig fmt --help
Usage: zig fmt [file]...
Formats the input files and modifies them in-place.
Arguments can be files or directories, which are searched
recursively.
Options:
-h, --help             Print this help and exit
--color [auto|off|on]  Enable or disable colored error messages
--stdin                Format code from stdin; output to stdout
--check                List non-conforming files and exit with an error
if the list is non-empty
--ast-check            Run zig ast-check on every file
--exclude [file]       Exclude file or directory from formatting
```
=> .github: add workflow for `zig fmt`

config.json
Convert `average_run_time` to an integer.
There are two reasons for this change:
1. Having the average run time as a float gives the impression of being exact, whereas the actual run time wildly varies due to a wide variety of reasons (e.g. how busy it is on the server). That fractional component will almost never actually conform the real situation.
2. jq is often used to work with track config.json config files (e.g. to add elements to it), and it will remove any trailing .0 fractional part from a number, which caused configlet lint to fail. Those JQ scripts then have to work around this by manually adding .0 to it.
This PR has been created as a draft and we will automatically merge it next week once the new `configlet` release is out.
See https://github.com/exercism/docs/pull/430 for …
=> config: convert `average_run_time` to an integer

exercises/practice/hamming/.meta/example.zig
Avoid potential confusion - this isn't yielding unicode code points.
Refs: #313
=> exercises(hamming): example: don't call a u8 a rune

exercises/practice/yacht/test_yacht.zig
Existing code only tested cases when dice in full-house and four-of-a-kind categories would have groups in certain positions when sorted. For example:
```
3,3,3,3,5 => four of a kind
3,3,3,5,5 => full house
```
but there were no tests for these cases
```
3,5,5,5,5 => four of a kind
3,3,5,5,5 => full house
```
I.e. the cases where group positions and lengths are switched around and a group with smaller number of elements goes first.
I saw several solutions which were hardcoding checks like
```c
if (sorted[0] == sorted[3]) {
// assume success in detecting four-of a kind
}
```
which is not correct, because it would fail in the `3,5,5,5,5` case while it shouldn't.
This PR adds a few more tests to check alternative ordering.
Not really sure if the new test case naming is good, a bit too vague, …
=> excersises(yacht): add order-independence tests to full-house and four-of-a-kind

config.json, exercises/practice/roman-numerals/.docs/instructions.md, exercises/practice/roman-numerals/.docs/introduction.md, exercises/practice/roman-numerals/.meta/config.json, exercises/practice/roman-numerals/.meta/example.zig, exercises/practice/roman-numerals/.meta/tests.toml, exercises/practice/roman-numerals/roman_numerals.zig, exercises/practice/roman-numerals/test_roman_numerals.zig
Based on @mk2s https://github.com/exercism/zig/pull/383/
=> Adding roman numerals

exercises/practice/rotational-cipher/rotational_cipher.zig
Missing imports cause build to fail meaning you don't receive the more user friendly `@compileError("please implement the rotate function")`
Add missing imports required by function contract
=> Fixed missing imports on rotation cipher exercise stub

exercises/practice/pig-latin/pig_latin.zig, exercises/practice/proverb/proverb.zig, exercises/practice/rna-transcription/rna_transcription.zig, exercises/practice/secret-handshake/secret_handshake.zig
As raised in https://github.com/exercism/zig/pull/449 some exercises do not contain the imports needed for users to receive the nicer `@compileError` prompting them to implement the needed function.
Make exercise flagged by @keiravillekode more consistent by including imports as appropriate. Note, secret handshake will continue to fail for missing types as implementing `Signal` is part of the work required by the exercise.
https://github.com/exercism/zig/pull/449#issuecomment-2748517767
=> Add missing std imports to show useful @compileError

exercises/practice/food-chain/.docs/instructions.append.md, exercises/practice/food-chain/.meta/example.zig, exercises/practice/food-chain/food_chain.zig, exercises/practice/food-chain/test_food_chain.zig, exercises/practice/house/.docs/instructions.append.md, exercises/practice/house/.meta/config.json, exercises/practice/house/.meta/example.zig, exercises/practice/house/house.zig, exercises/practice/house/test_house.zig, exercises/practice/twelve-days/.docs/instructions.append.md, exercises/practice/twelve-days/.meta/example.zig, exercises/practice/twelve-days/test_twelve_days.zig, exercises/practice/twelve-days/twelve_days.zig
We allow errors to be returned from recite()
This change breaks existing community solutions.
=> food-chain,house,twelve-days error reporting
