exercism/zig

config/maintainers.json
This pull request fulfills the first step of my tasks list as referenced below:
>     1. Add myself to the list of maintainers.
https://github.com/exercism/zig/issues/1#issuecomment-755826464
=> Add massivelivefun to list of maintainers

config/maintainers.json
Reverts exercism/zig#3
Need to correct double parent by rebasing appropriately.
=> Revert "Add massivelivefun to list of maintainers"

docs/ABOUT.md, docs/INSTALLATION.md, docs/LEARNING.md, docs/RESOURCES.md, docs/TESTS.md
This pull request fulfills the second step of my tasks list as referenced below:
>     2. Update the docs/ files to be filled with content related to Zig.
https://github.com/exercism/zig/issues/1#issuecomment-755826464
=> Add zig docs

docs/SNIPPET.txt
Forgot to add this file.
This PR works in conjunction with the second step of list mentioned below:
>      2. Update the docs/ files to be filled with content related to Zig.
#1 (comment)
=> Add snippet file

docs/LEARNING.md, docs/RESOURCES.md
Simple clean up of these files.
=> Tidy up LEARNING.md and RESOURCES.md

config.json
- Corrections to inconsistent values for keys and nonexistent concepts that simply do not exist in Zig.
=> Standardize config.json values

config/maintainers.json
=> Maintainer: Add KOTP

exercises/practice/binary-search/.meta/tests.toml, exercises/practice/leap/.meta/tests.toml
This PR fixes some issues in the `tests.toml` files.
Pinging @ErikSchierboom for review.
=> Fix invalid tests.toml files

config/maintainers.json
=> Add hiljusti to zig track maintainers

.github/bin/install-zig.sh, .github/workflows/tests.yml
=> ci: refactor zig installation process

exercises/practice/binary-search/.meta/config.json, exercises/practice/collatz-conjecture/.meta/config.json, exercises/practice/darts/.meta/config.json, exercises/practice/difference-of-squares/.meta/config.json, exercises/practice/grains/.meta/config.json, exercises/practice/hamming/.meta/config.json, exercises/practice/hello-world/.meta/config.json, exercises/practice/isogram/.meta/config.json, exercises/practice/leap/.meta/config.json, exercises/practice/pangram/.meta/config.json, exercises/practice/proverb/.meta/config.json, exercises/practice/queen-attack/.meta/config.json, exercises/practice/resistor-color-duo/.meta/config.json, exercises/practice/resistor-color/.meta/config.json, exercises/practice/rna-transcription/.meta/config.json, exercises/practice/secret-handshake/.meta/config.json, exercises/practice/space-age/.meta/config.json, exercises/practice/triangle/.meta/config.json, exercises/practice/two-fer/.meta/config.json
This runs the `bin/configlet fmt --update` command to
reformat the exercise configs.
=> Reformat exercise config files

exercises/practice/difference-of-squares/.meta/tests.toml, exercises/practice/grains/.meta/tests.toml, exercises/practice/hamming/.meta/tests.toml, exercises/practice/leap/.meta/tests.toml, exercises/practice/queen-attack/.meta/tests.toml, exercises/practice/resistor-color/.meta/tests.toml, exercises/practice/triangle/.meta/tests.toml
=> exercises: sync tests.toml description values

exercises/practice/hello-world/.meta/example.zig, exercises/practice/hello-world/test_hello_world.zig
For consistency with other tracks
=> hello-world: fix casing

config.json
Closes: #21
---
Ideally, I'd prefer if we could merge at least the below PRs before we merge this one.
=> config: set track to active

exercises/practice/triangle/test_triangle.zig
Follow-up for commit ec8d039670fe.
Refs: #136
=> exercises(triangle): rename test

config.json, exercises/practice/resistor-color-duo/.meta/example.zig, exercises/practice/resistor-color-duo/.meta/tests.toml, exercises/practice/resistor-color-duo/resistor_color_duo.zig, exercises/practice/resistor-color-duo/test_resistor_color_duo.zig
Closes: #202
---
For later: consider changing to `usize`.
=> exercises(resistor-color-duo): remove test case for array of length 3

exercises/practice/triangle/.meta/example.zig, exercises/practice/triangle/triangle.zig
And inline those functions in the example.
Closes: #216
=> exercises(triangle): remove stubs for private functions

config.json
This will help with https://github.com/exercism/zig/pull/289
=> Use `jq` to format `config.json`

exercises/practice/anagram/.docs/instructions.md, exercises/practice/atbash-cipher/.docs/instructions.md, exercises/practice/atbash-cipher/.meta/config.json, exercises/practice/bob/.meta/tests.toml, exercises/practice/bob/test_bob.zig, exercises/practice/collatz-conjecture/.docs/instructions.md, exercises/practice/collatz-conjecture/.docs/introduction.md, exercises/practice/collatz-conjecture/.meta/config.json, exercises/practice/eliuds-eggs/.docs/introduction.md, exercises/practice/grains/.meta/config.json, exercises/practice/hamming/.docs/instructions.md, exercises/practice/hamming/.docs/introduction.md, exercises/practice/hamming/.meta/config.json, exercises/practice/knapsack/.docs/instructions.md, exercises/practice/knapsack/.docs/introduction.md, exercises/practice/leap/.meta/config.json, exercises/practice/luhn/.docs/instructions.md, exercises/practice/luhn/.docs/introduction.md, exercises/practice/pig-latin/.meta/tests.toml, exercises/practice/pig-latin/test_pig_latin.zig, exercises/practice/pythagorean-triplet/.docs/instructions.md, exercises/practice/pythagorean-triplet/.docs/introduction.md, exercises/practice/pythagorean-triplet/.meta/config.json, exercises/practice/rna-transcription/.docs/instructions.md, exercises/practice/rna-transcription/.meta/config.json, exercises/practice/square-root/.docs/instructions.md, exercises/practice/square-root/.docs/introduction.md, exercises/practice/sum-of-multiples/.docs/instructions.md, exercises/practice/sum-of-multiples/.docs/introduction.md, exercises/practice/yacht/.meta/config.json
=> Sync exercises

config.json, exercises/practice/phone-number/.docs/instructions.md, exercises/practice/phone-number/.docs/introduction.md, exercises/practice/phone-number/.meta/config.json, exercises/practice/phone-number/.meta/example.zig, exercises/practice/phone-number/.meta/tests.toml, exercises/practice/phone-number/phone_number.zig, exercises/practice/phone-number/test_phone_number.zig
As suggested in https://github.com/exercism/zig/issues/229 we use an optional.
=> Add phone-number exercise

exercises/practice/grains/.docs/instructions.md, exercises/practice/grains/.docs/introduction.md, exercises/practice/largest-series-product/.meta/tests.toml, exercises/practice/luhn/.docs/instructions.md, exercises/practice/luhn/.docs/introduction.md, exercises/practice/sieve/.docs/instructions.md
No changes are needed in largest-series-product test source code, as we don't use error strings.
[no important files changed]
=> Sync practice exercises

exercises/practice/eliuds-eggs/.docs/introduction.md, exercises/practice/phone-number/.docs/instructions.md
=> Sync exercise instructions

config.json
1 -> 2 - acronym
1 -> 4 - all-your-base
1 -> 3 - allergies
1 -> 3 - anagram
1 -> 2 - armstrong-numbers
1 -> 4 - atbash-cipher
1 -> 3 - binary-search
1 -> 3 - bob
1 -> 2 - collatz-conjecture
1 -> 2 - darts
1 -> 2 - difference-of-squares
1 -> 3 - dnd-character
1 -> 2 - grains
1 -> 2 - hamming
1 -> 4 - house
1 -> 3 - isbn-verifier
1 -> 4 - luhn
1 -> 4 - matching-brackets
1 -> 3 - perfect-numbers
1 -> 3 - proverb
1 -> 3 - queen-attack
1 -> 3 - secret-handshake
1 -> 3 - sieve
1 -> 4 - yacht
=> Adjust exercise difficulties

exercises/practice/eliuds-eggs/.docs/instructions.append.md
From [forum](https://forum.exercism.org/t/misleading-instructions-in-eliuds-eggs/19258)
=> Avoid builtin functions for eliuds-eggs

config.json, exercises/practice/resistor-color-trio/.docs/instructions.md, exercises/practice/resistor-color-trio/.meta/config.json, exercises/practice/resistor-color-trio/.meta/example.zig, exercises/practice/resistor-color-trio/.meta/tests.toml, exercises/practice/resistor-color-trio/resistor_color_trio.zig, exercises/practice/resistor-color-trio/test_resistor_color_trio.zig
Update resistor-color difficulties to 2
=> Add resistor-color-trio

exercises/practice/resistor-color-trio/test_resistor_color_trio.zig
We verify there are no memory leaks in the event of memory allocation failure.
=> resistor-color-trio - checkAllAllocationFailures

exercises/practice/two-fer/two_fer.zig
=> two-fer omits anyerror
